### PR TITLE
number_guessing_game

### PR DESCRIPTION
**Pull request by Jinal4502**
Computer guesses a number and you have to check whether it's correct or not!

### CODE REVIEW

**Comment by manisha069** [comment]
what are you doing? closing and opening... are you having some troubles?

**Comment by Jinal4502** [comment]
Actually I am new to git hub...So I was just checking that what happens if
I close my pull request. To get my pull request accepted do I need to keep
it open ?

**Comment by Jinal4502** [comment]
I got it...I will have to keep it open...So I am keeping my pull request
open to get it accepted.
Sorry for the trouble:)

**Comment by manisha069** [comment]
Yes, to be properly merged you need to keep yr request open and then the owner of repository decided whether they want to merge yr request or not.

**Comment by Jinal4502** [comment]
Yes !

**Comment by manisha069** [comment]
It is not an issue, I like that you are new things...even I am new! no trouble
Are you participating in hacktoberfest?

**Comment by Jinal4502** [comment]
Yes, I got to know about this repo from the meeting which we had on October
11th.

**Comment by manisha069** [comment]
well thats great to know..i'll yr merge your PR with hacktoberfest accepted label then...Congratulations on getting one!

**Comment by Jinal4502** [comment]
Thank you so much Manisha !

**Comment by manisha069** [comment]
My Pleasure! keep going!!

**Pull request merged**
